language: python
python:
  - "3.6"
services:
    - mysql
env:
    global:
     - TRAVIS=true
before_install:
    - sudo apt update -y && apt upgrade -y && apt install python3 python3-venv python3-dev python3-pip libpng-dev libfreetype6-dev -y
    - sudo mysql -e 'source jarvis_schema.sql'
install:
  - pip install --upgrade setuptools
  - pip install -r dependencies.txt
script:
  - bash bin/jarvis.sh start
  - bash bin/jarvis.sh check
notifications:
  email:
    recipients:
      - kirillrudenko1994@gmail.com
    on_success: always 
    on_failure: always 